"""empty message

Revision ID: 3297f149eb4a
Revises: 6229f7f53158
Create Date: 2020-07-12 01:37:13.082742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3297f149eb4a'
down_revision = '6229f7f53158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.ARRAY(sa.Text()), nullable=True))
    op.add_column('venue', sa.Column('genres', sa.ARRAY(sa.Text()), nullable=True))
    op.alter_column('show', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'genres')
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###
