"""empty message

Revision ID: 6229f7f53158
Revises: b956c1503d42
Create Date: 2020-07-12 01:12:24.211337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6229f7f53158'
down_revision = 'b956c1503d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'genres')
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('genres', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
