"""empty message

Revision ID: 8ee03f39050f
Revises: ac2117369ba6
Create Date: 2020-07-11 23:03:55.462065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ee03f39050f'
down_revision = 'ac2117369ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'past_shows')
    op.drop_column('artist', 'upcoming_shows_count')
    op.drop_column('artist', 'past_shows_count')
    op.drop_column('artist', 'upcoming_shows')
    op.add_column('show', sa.Column('start_time', sa.String(length=120), nullable=True))
    op.drop_column('venue', 'past_shows')
    op.drop_column('venue', 'upcoming_shows_count')
    op.drop_column('venue', 'past_shows_count')
    op.drop_column('venue', 'upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('upcoming_shows', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('venue', sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('past_shows', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('show', 'start_time')
    op.add_column('artist', sa.Column('upcoming_shows', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('artist', sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('past_shows', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
